excluded:
  - Lion/Study

disabled_rules: # 执行时排除掉的规则
  - opening_brace
  - multiple_closures_with_trailing_closure

type_name:
  excluded: 
    - T
    - S

identifier_name:
  excluded:
    - i
    - j
    - k
    - id
    - to
  allowed_symbols:
    - _

line_length: 
  ignores_comments: true
  warning: 150
  error: 300